name: Build Bigdroid Project

on:
  push:
    tags:
      - '*'  # Run on any new tag

jobs:
  publish_release:
    name: Building Bigdroid project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Use latest stable version

      - name: Run Bigdroid Builder
        uses: bigdroid/action-build@main  # Replace 'main' if HEAD doesn't exist
        env:
          API_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
