name: Build Bigdroid Project

on:
  push:
    branches:
      - '*'      # Trigger on push to any branch
    tags:
      - '*'      # Trigger on push of any tag
  workflow_dispatch:   # Allow manual trigger from the GitHub UI

jobs:
  publish_release:
    name: Building Bigdroid project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Bigdroid Builder
        uses: bigdroid/action-build@main  # Replace 'main' with the correct branch or tag if needed
        env:
          API_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
